#!/usr/bin/env python3

# Извлекает содержимое из таблицы excel
#
# $1 — имя файла с таблицами
# $2 — имя страницы, из которой надо извлечь адреса
#
# Выводит содержимое на stdout
# Ячейки разделяются переносом строки
# Строки разделяются нулевым байтом


import sys
import re
from xlrd import open_workbook


#filename = sys.argv[1]
#sheet = sys.argv[2]
filename = '/_reports/2014.09.15.xls'
sheet = 'ФРИСОЛАК'


result = []

book = open_workbook(filename)
sheet = book.sheet_by_name(sheet)
for i in range(sheet.nrows):
    row = sheet.row(i)
    if row[0].ctype == 2: # 2 — XL_CELL_NUMBER, то есть в ячейке число
        # Если в первой ячейке номер строки, то это строка с адресом
        for cell in row:
            print(cell.value)
        print('\0')
