#!/usr/bin/env python3

# Извлекает адреса из файла с таблицами
#
# $1 — имя файла с таблицами
# $2 — имя страницы, из которой надо извлечь адреса
# $3 — номер колонки, в которой лежат адреса


import sys
import re
from xlrd import open_workbook


#filename = '/root/s/zdrav/reports/2014.09.15.xlsx'
filename = sys.argv[1]
sheet = sys.argv[2]
colnum = int(sys.argv[3])


result = []

book = open_workbook(filename)
sheet = book.sheet_by_name(sheet)
for i in range(sheet.nrows):
    row = sheet.row(i)
    if row[0].ctype == 2: # 2 — XL_CELL_NUMBER, то есть в ячейке число
        # Если в первой ячейке номер строки, то это строка с адресом
        addr = row[colnum].value
        result.append(addr)

for addr in result:
    print(addr)
