#!/usr/bin/env python3

# Распечатывает имена страниц в файле с таблицами
# $1 — имя файла с таблицами

import sys
import os
from xlrd import open_workbook

#filename = '/root/s/zdrav/reports/2014.09.15.xlsx'
filename = sys.argv[1]

book = open_workbook(filename)
for sheet_name in book.sheet_names():
    print(sheet_name)
